import brain from '@/components/dashboardlayout/brain';
import clip from '@/components/dashboardlayout/clip-board';
import meet from '@/components/dashboardlayout/meet';
import { AdminStepCardProps, StepCardProps } from '@/lib/types';

export const steps: StepCardProps[] = [
  {
    step: 1,
    title: 'Knowing You',
    description: 'An interactive quiz to test your abilities.',
    icon: brain,
    buttonText: 'Start Now',
    buttonBgColor: 'bg-[#FBBC04]',
    gradientBg: 'bg-yellow-gradient',
    action: '/dashboard/quiz',
    eventStartDate: new Date('2025-04-13T00:00:00'),
    eventEndDate: new Date('2025-04-14T00:00:00'),
  },
  {
    step: 2,
    title: 'Task Round',
    description: 'Solve and create! Impress us with your solution.',
    icon: clip,
    buttonText: 'View Tasks',
    buttonBgColor: 'bg-[#4285F4]',
    gradientBg: 'bg-blue-gradient',
    action: '/dashboard/task-round',
    eventStartDate: new Date('2025-04-14T00:00:00'),
    eventEndDate: new Date('2025-04-16T12:59:00'),
  },
  {
    step: 3,
    title: 'Personal Interview',
    description: 'The final step, a conversation to seal your place.',
    icon: meet,
    buttonText: 'View Timing',
    buttonBgColor: 'bg-[#EA4335]',
    gradientBg: 'bg-red-gradient',
    action: '#',
    eventStartDate: new Date('2025-04-17T00:00:00'),
    eventEndDate: new Date('2025-04-18T03:00:00'),
  },
  {
    step: 4,
    title: 'Coding Contest',
    description: 'Prove your coding prowess in timed algorithmic challenges.',
    icon: clip,
    buttonText: 'Start Now',
    buttonBgColor: 'bg-[#4285F4]',
    gradientBg: 'bg-blue-gradient',
    action: '/dashboard/task-round',
    eventStartDate: new Date('2025-04-15T12:00:00'),
    eventEndDate: new Date('2025-04-15T16:00:00'),
  },
];

export const adminSteps: AdminStepCardProps[] = [
  {
    step: 1,
    title: 'Create Quiz (Knowing You)',
    description: 'Set up the quiz for candidates.',
    icon: brain,
    buttonText: 'Create Quiz',
    buttonBgColor: 'bg-[#FBBC04]',
    gradientBg: 'bg-yellow-gradient',
    action: '/admin/dashboard/create-quiz',
    disabled: false,
  },
  {
    step: 2,
    title: 'Upload Task',
    description: 'Add the challenge tasks here.',
    icon: clip,
    buttonText: 'Upload Disabled',
    buttonBgColor: 'bg-[#4285F4]',
    gradientBg: 'bg-blue-gradient',
    action: '/dashboard/task-round',
    disabled: true,
  },
  {
    step: 3,
    title: 'All Candidates',
    description: 'Review all submitted entries.',
    icon: meet,
    buttonText: 'View Candidates',
    buttonBgColor: 'bg-[#EA4335]',
    gradientBg: 'bg-red-gradient',
    action: '/admin/dashboard/all-candidates',
    disabled: false,
  },
];
