export const androidTasks = [
  {
    year: 1,
    tasks: [
      {
        type: 'Attendance Tracker',
        title: 'Smart Attendance Buddy',
        description: [
          '🎯 Task Overview: ',
          'Create a Smart Attendance Buddy app that helps students track attendance and understand their eligibility status.',
          '',
          'Screen 1 - Attendance Input',
          'Input fields for Name and Branch.',
          'Add the subject name.',
          'Input number of classes attended.',
          'Input total number of classes conducted.',
          'Button to calculate attendance.',
          '',
          'Screen 2 - Attendance Result',
          'Display attendance percentage.',
          'Show eligibility message based on logic:',
          '≥75% → Safe zone.',
          '60–74% → Warning.',
          '<60% → Danger zone.',
          'Submission Guidelines',
          'Submit source code as a GitHub repository.',
          'Include a README with app screenshots.',
          'Mention any bonus features implemented.',
        ],
        link: '',
        criteria: [
          'Logical implementation of attendance calculation.',
          'Clean UI design.',
          'Proper input validation.',
          'Good code structure.',
        ],
        browniePoints: [
          'Store multiple subjects using RecyclerView.',
          'Use color indicators (Green/Yellow/Red).',
          'Persist data using SharedPreferences.',
        ],
        imageUrl: '',
      },
    ],
  },
  {
    year: 2,
    tasks: [
      {
        type: 'api-offline-news-reader',
        title: 'News Reader App',
        description: [
          '🎯 Task Overview: ',
          'Build a News Reader Android App that fetches live news articles from a public API and allows users to save articles locally for offline reading. The app will demonstrate API integration, offline storage, list rendering, and in-app article viewing.',
          'Students must generate and use their own API key.',
          'App must support both online fetch and offline saved reading.',
          '',
          'Screen 1 – News Feed',
          'Purpose: To fetch and display the latest news articles from the API.',
          'Fetch latest headlines from NewsAPI on screen load.',
          'Display articles in a scrollable list (RecyclerView / LazyColumn).',
          'Each news item should include:',
          'Article image.',
          'Title.',
          'Source name.',
          '"Save for Later" button.',
          'Save for Later:',
          'On clicking "Save for Later", store that article locally.',
          'Use RoomDB or DataStore.',
          'Save at least:',
          'Title.',
          'Description.',
          'Source.',
          'Navigation:',
          'On clicking any news item, open the full article (Must open inside app experience, it should not switch to external browser app) for reading complete news.',
          'Screen 2 - Saved Articles (Offline Screen)',
          'Purpose: To display articles saved locally for offline reading.',
          'Load data only from local storage.',
          'This screen must work without internet.',

          'UI: Scrollable list of saved articles',
        ],
        link: 'https://newsapi.org',
        criteria: [
          'Recycler View for news list',
          'Proper API integration and data parsing',
          'Working Save for Later feature with local storage',
          'Clean and modular code structure',
          'Proper loading, error, and empty states',
        ],
        browniePoints: [
          'Follow a good architecture pattern (recommended: MVVM)',
          'RoomDB integration with Entity + DAO + Database setup',
          'Dark mode support',
          'Swipe to delete saved articles',
          'Creative and polished UI enhancements',
        ],
        imageUrl: '',
      },
    ],
  },
];

export const mlTasks = [
  {
    year: 1,
    tasks: [
      {
        type: 'Task: Neural Network from Scratch',
        title: 'Task 1: Neural Network from Scratch',
        description: [
          'Objective: ',
          'Implement a basic neural network from scratch to classify simple datasets like XOR or MNIST (digits 0-1 for simplicity).',
          'Tools Allowed: ',
          'PyTorch (without using nn.Module, only use torch.Tensor) OR Pure Python with NumPy',
          'What we expect:',
          'Manual implementation of forward and backward propagation, use of activation functions (ReLU or Sigmoid), a proper training loop with loss computation (MSE or CrossEntropy), and a plot/display of loss reduction over epochs with the final classification accuracy.',
          'Submission: ',
          'Jupyter Notebook (.ipynb) or Python script (.py) including a README explaining your architecture and approach.',
        ],
        link: '',
        criteria: [
          'Correct implementation of forward and backward propagation',
          'Proper use of activation functions',
          'Effective training loop and loss reduction demonstration',
          'Overall classification accuracy and code quality',
        ],
        browniePoints: [
          'Bonus for additional optimization techniques or creative visualization methods',
        ],
        imageUrl: '',
      },
      {
        type: 'Task: DataFrame Manipulation and Modeling',
        title: 'Task 2: DataFrame Manipulation and Modeling',
        description: [
          'Objective: ',
          'Work with a real-world mobile dataset to perform comprehensive exploratory data analysis (EDA) and build a basic classification model to predict user behavior patterns.',
          'Tools Allowed: Python, Pandas, NumPy, Matplotlib/Seaborn for visualization, and Scikit-learn for modeling.',
          'What to Include:',
          'Data Loading and Cleaning: Handle missing values, encode categorical variables (like Operating System or Gender), and scale numerical data (like App Usage Time or Battery Drain).',
          'DataFrame Operations & EDA: Group and sort data to find trends. Calculate statistical summaries (e.g., average screen-on time per behavior class).',
          'Visualization & Insights: Create at least 3 meaningful graphs using matplotlib or seaborn (e.g., correlation heatmaps, scatter plots) highlighting 3-5 interesting insights about how device usage impacts behavior classes.',
          'Model Training & Evaluation: Train a basic machine learning model (e.g., Logistic Regression, Decision Tree, or K-Nearest Neighbors) to predict the "User Behavior Class". Evaluate it using accuracy and a confusion matrix.',
          'Submission:',
          'Jupyter Notebook (.ipynb) or Python script (.py) along with a README describing your data insights and modeling approach.',
        ],
        link: 'https://www.kaggle.com/datasets/valakhorasani/mobile-device-usage-and-user-behavior-dataset/data',
        criteria: [
          'Data cleaning and manipulation effectiveness',
          'Quality and depth of exploratory data analysis',
          'Insightfulness and clarity of visualizations',
          'Correctness of model implementation and evaluation metrics',
          'Overall code quality and readability',
        ],
        browniePoints: [
          'Bonus for comparing the performance of multiple different classification models.',
          'Extra credit for implementing an algorithm (like KNN or Logistic Regression) entirely from scratch using only NumPy.',
        ],
        imageUrl: '',
      },
    ],
  },
  {
    year: 2,
    tasks: [
      {
        type: 'Graph RAG Chatbot with Auto-Updating Memory',
        title: 'Task 1: Graph RAG Chatbot with Auto-Updating Memory',
        description: [
          'Objective:',
          'Build a chatbot that uses a knowledge graph as its memory. When a user tells the chatbot something new, it should automatically extract that information and add it to the graph. When the user asks a question, the chatbot should retrieve relevant context from the graph and use it to answer. It should be able to support dedicated memory for multiple users.',
          'Tools Allowed:',
          'NetworkX or Neo4j for the knowledge graph.',
          'HuggingFace transformers or any free LLM API (Gemini free tier, Groq, etc.) for the language model.',
          'spaCy or NLTK for basic entity extraction.',
          'Streamlit or Gradio for a simple chat interface.',
          'Results:',
          '- At least 10 example inputs that add information to the graph.',
          '- At least 5 queries that correctly use the stored graph context to answer.',
          "- Bonus points for a live visualisation of the graph using NetworkX's drawing tools or any other library.",
          '- Reflection (200–300 words):',
          'What kinds of inputs your extraction pipeline handles well and where it breaks.',
          'One limitation of using a graph structure for this kind of memory.',
          'Submission Format:',
          '📁 GitHub repo or ZIP with code',
          '📝 README with setup instructions, example queries, and a screenshot of the graph visualisation',
        ],
        link: '',
        criteria: [
          'Accuracy of information storage and retrieval from the graph',

          'Relevance of context pulled during a query',
          'Cleanliness and logical structure of the final graph',
        ],
        browniePoints: [
          'Working Streamlit or Gradio demo',
          'Live graph visualisation during conversation',
        ],
        imageUrl: '',
      },
      {
        type: 'Task: Train a Reinforcement Learning Agent for FrozenLake',
        title: 'Task 2: Train a Reinforcement Learning Agent for FrozenLake',
        description: [
          'Objective: ',
          'Train an RL agent from scratch to solve FrozenLake-v1 from OpenAI Gymnasium.',
          'The goal of the agent is to navigate to the end goal without falling in holes.',
          'Tools Allowed:',
          'OpenAI Gymnasium.',
          'PyTorch or NumPy.',
          'Matplotlib for plotting.',
          'Not Allowed:',
          'Stable Baselines, RLlib, or any pre-built RL algorithm library.',
          'Pre-trained weights.',
          'You must write the training loop yourself',
          'Algorithm:',
          'Your choice. Pick one and justify it.',
          'Contraints:',
          'Training must complete within 1000 episodes.',
          'Your agent must demonstrably beat a random policy, show this with numbers.',
          'Results:',
          'Reward curve: episode number vs total reward, smoothed with a rolling average over episodes.',
          'Average reward of your agent vs a random policy over 100 test episodes.',
          'Reflection (200–300 words):',
          'What effect did changing the learning rate or discount factor have.',
          'At what point in training did the agent start meaningfully improving and why you think that is.',
          'Submission Format:',
          '📁 Colab notebook (.ipynb) or GitHub repo',
          '📝 README with algorithm used, results summary, and how to run the code',
        ],
        link: 'https://gymnasium.farama.org/environments/toy_text/frozen_lake/#frozen-lake',
        criteria: [
          'Correctness and clarity of training loop with justified hyperparameters',
          'Agent performance vs random policy',
          'Depth of reflection on hyperparameter tuning',
        ],
        browniePoints: [
          'Training on slippery mode (is_slippery=True) with reward comparison against random policy',
        ],
        imageUrl: '',
      },
    ],
  },
];

export const designTasks = [
  {
    year: 1,
    gfx: [
      {
        description: [
          'Task 1: Logo Design – Zealicon Annual Fest',
          'Theme: Filmy Fiesta – Lights. Camera. Celebration.',
          'The logo should',
          'Logo must be in SVG format.',
          'Use preferably figma, adobe suit etc. No use of Canva.',
          'Reflect the apt energy, celebration & youth culture.',
          'Be adaptable across merchandise, posters & social media.',
          'Represent fest identity clearly.',
          'Be scalable and versatile.',
          'You may:',
          'Create a symbolic mark.',
          'Use typography-based logo.',
          'Combine icon + wordmark.',
          'Deliverables:',
          'Primary logo.',
          'Monochrome version.',
          'Icon-only version.',
          'Mockup (T-shirt / Banner / Social Media DP).',
          'Logo should be in SVG format.',
          'REMARK:',
          'AI MAY BE USED FOR BASIC IDEATION PURPOSE ONLY. ANY LOGO GENERATED BY AI OR A COPY OF ENTIRE IDEATION WILL BE DISQUALIFIED.',
          'Copy of any existing logo will be disqualified.',
          'Task 2: Social Media Post - Zealicon Announcement',
          'Design a social media post announcing:',
          '🎉 Zealicon – Annual Fest',
          'Theme: Filmy Fiesta – Lights. Camera. Celebration.',
          'The post must include:',
          'Fest Name.',
          'Theme (leave blank in submission template).',
          'Dates (placeholder allowed).',
          'Tagline.',
          'Organized by (College Name).',
          'Call to Action (Register Now / Stay Tuned).',
          'Design should be:',
          'Eye-catching.',
          'Shareable on Instagram & LinkedIn.',
          'Youth-centric & vibrant.',
          'Visually balanced.',
          'Bonus',
          'Carousel version.',
          'Story version.',
          'Motion concept idea.',
          'Remark',
          'AI MAY BE USED FOR BASIC IDEATION PURPOSE ONLY. ANY POST GENERATED BY AI WILL BE DISQUALIFIED.',
        ],
        link: '',
        criteria: [
          'Relevance to industry',
          'Typography quality',
          'Color scheme harmony',
          'Composition & visual hierarchy',
        ],
        browniePoints: [
          'Vector format submission',
          'Multiple variations',
          'Branch reasoning explanation',
          'Real-world mockups',
        ],
      },
    ],
    ux: [
      {
        description: [
          'Task 1: Redesign - Zomato / Blinkit (Choose One)',
          'Redesign either:',
          'Zomato (Food delivery experience) or Blinkit (Quick commerce grocery experience)',
          'Focus Areas:',
          'Home screen clarity.',
          'Product / Restaurant discovery.',
          'Filtering & search UX.',
          'Checkout flow improvement.',
          'Reducing cognitive overload.',
          'Deliverables:',
          'Competitive analysis.',
          'Wireframes.',
          'High-fidelity UI.',
          'Interactive prototype.',
          'Remark',
          'AI CAN BE USED FOR IDEATION AND WIREFRAMING PROCESS ONLY.',
          'Task 2: Redesign – Uber / Ola (Choose One)',
          'Redesign either:',
          'Uber or Ola.',
          'Focus On:',
          'Booking flow simplification.',
          'Fare transparency.',
          'Ride tracking experience.',
          'Safety features visibility.',
          'Accessibility improvements.',
          'Deliverables:',
          'User flow diagram.',
          'Wireframes.',
          'Final UI screens.',
          'Prototype.',
          'Remark:',
          'AI CAN BE USED FOR IDEATION AND WIREFRAMING PROCESS ONLY.',
        ],
        link: '',
        criteria: [
          'User flow improvements',
          'Accessibility',
          'Problem identification clarity',
          'UX reasoning',
        ],
        browniePoints: [
          'Design system implementation',
          'Dark mode',
          'Micro-interactions',
          'Usability testing insights',
        ],
      },
    ],
    vfx: [
      {
        description: [
          'Task: Animate a Mascot',
          'Create a short animated clip (10–20 seconds) featuring a mascot.',
          'You may:',
          'Create your own original mascot OR Choose an existing mascot (e.g., Android bot, college mascot, etc.).',
          'Animation Requirements(any 2 or more):',
          'Character introduction.',
          'Simple personality expression.',
          'Movement (walk, jump, wave, react, etc.)',
          'Clean motion principles (ease in/out, anticipation, squash & stretch where applicable).',
          'Submission Format:',
          'MP4 / GIF.',
          '10–20 seconds.',
          '1080x1080 or 1920x1080.',
          'Focus On:',
          'Fluidity of motion.',
          'Timing & spacing.',
          'Character personality.',
          'Visual consistency.',
          'Remark:',
          'Use any application of your choice. Use of Canva is prohibited.',
        ],
        link: '',
        criteria: [
          'Animation principles',
          'Smooth transitions',
          'Creativity',
          'Character expression',
        ],
        browniePoints: [
          'Sound design',
          'Loop animation',
          'Secondary motion details',
          'Branding integration',
        ],
      },
    ],
  },
  {
    year: 2,
    gfx: [
      {
        description: [
          'Task 1: Design a Cinematic Movie Poster with Complete Visual Identity',
          'Create a visual identity and cinematic poster for an original fictional movie.',
          'Concept Requirement',
          '- The movie must have:',
          'A defined genre (Thriller / Sci-Fi / Drama / Psychological / Romance / Action / Mystery, etc.).',
          'Clear story premise (2–3 line synopsis).',
          'Defined target audience.',
          'Emotional tone & mood direction.',
          'Focus Areas',
          'Strong storytelling through visuals.',
          'Clear genre communication.',
          'Cinematic composition.',
          'Consistent visual language.',
          'Typography hierarchy (Title, Tagline, Credits block).',
          'Scalable poster system (works across formats).',
          'Trend awareness without copying existing movie posters.',
          'Deliverables',
          '1️) Concept Sheet',
          'Movie Title.',
          'Tagline.',
          'Genre.',
          'Short Synopsis ( 2-3 lines ).',
          'Target audience persona.',
          'Moodboard references (style direction only).',
          '2) Poster System',
          'Primary theatrical poster (vertical).',
          'Alternate version (variation in layout or color treatment).',
          'Poster must include:',
          'Title.',
          'Tagline.',
          'Cast names (fictional allowed).',
          'Production studio (fiction allowed).',
          'Release date.',
          'Credits block.',
          '3️) Visual Identity Elements',
          'Title typography system.',
          'Color palette.',
          'Graphics elements (textures, overlays, symbols, patterns).',
          'Grid system or layout logic.',
          '4) Mockups (Any 2–3)',
          'Theatre billboard.',
          'Bus stop poster.',
          'OTT platform thumbnail.',
          'Instagram promotional post.',
          'Movie ticket design.',
          '⚠️ Important Rules',
          'MINIMAL USE OF AI - AI may be used only for basic ideation or reference inspiration.',
          'No copying or recreating existing movie posters.',
          'No use of existing movie branding.',
          'All concepts must be original.',
        ],
        link: '',
        criteria: [
          'Originality & creativity.',
          'Concept clarity.',
          'Storytelling impact.',
          'Visual consistency.',
          'Typography quality.',
          'Cinematic feel.',
          'Practical usability across platforms.',
        ],
        browniePoints: [
          'Monochrome poster variation',
          'Motion poster concept idea',
          'Trailer title animation concept (brief explanation)',
          'Detailed layout rationale',
          'Branding scalability explanation',
        ],
        imageUrl: '',
      },
    ],
    ux: [
      {
        description: [
          'Task 1: Redesign PNB ONE App Homepage',
          'Redesign the homepage of the PNB ONE mobile banking app.',
          'Your goal is to improve clarity, simplify navigation, and enhance overall usability while maintaining banking-grade trust and security.',
          'You must:',
          'Identify at least 2 UX flaws.',
          'Improve navigation & clarity.',
          'Reduce cognitive overload.',
          'Improve accessibility.',
          '🔎 Required Deliverables:',
          'User research (Mandatory).',
          'User flow (Mandatory).',
          'Persona (Mandatory).',
          'Competitive analysis.',
          'UX audit of current homepage.',
          'Wireframes.',
          'High-fidelity UI.',
          'Interactive prototype.',
          'Design style guide.',
          '📝 Brief Explanation Required:',
          'What UX flaws did you find?',
          'Why are they problematic?',
          'How does your redesign solve them?',
          'What measurable improvement can it create?',
          'Remark:',
          'AI CAN BE USED FOR IDEATION AND WIREFRAMING PROCESS ONLY.',
        ],
        link: '',
        criteria: [
          'User flow optimization',
          'Accessibility compliance',
          'Visual hierarchy',
          'Platform consistency',
          'UX reasoning clarity',
        ],
        browniePoints: [
          'Micro-interaction design',
          'Dark mode implementation',
          'User testing results',
          'Full design system documentation',
          'Case study documentation',
        ],
        imageUrl: '',
      },
    ],
    vfx: [
      {
        description: [
          'Task: Animate a Mascot',
          'Create a short animated clip (10–20 seconds) featuring a mascot.',
          'You may:',
          'Create your own original mascot OR Choose an existing mascot (e.g., Android bot, college mascot, etc.).',
          'Animation Requirements(any 2 or more):',
          'Character introduction.',
          'Simple personality expression.',
          'Movement (walk, jump, wave, react, etc.)',
          'Clean motion principles (ease in/out, anticipation, squash & stretch where applicable).',
          'Submission Format:',
          'MP4 / GIF.',
          '10–20 seconds.',
          '1080x1080 or 1920x1080.',
          'Focus On:',
          'Fluidity of motion.',
          'Timing & spacing.',
          'Character personality.',
          'Visual consistency.',
          'Remark:',
          'Use any application of your choice. Use of Canva is prohibited.',
        ],
        link: '',
        criteria: [
          'Animation principles',
          'Smooth transitions',
          'Creativity',
          'Character expression',
        ],
        browniePoints: [
          'Sound design',
          'Loop animation',
          'Secondary motion details',
          'Branding integration',
        ],
      },
    ],
  },
];

export const webDevTasks = [
  {
    year: 1,
    tasks: [
      {
        title: 'Task 1: GitHub Profile & Repository Explorer (Frontend)',
        description: [
          'Objective',
          'Build a frontend application to search and display GitHub user profiles and repositories.',
          'UI should be clean and good.',
          'Core Functional Requirements',
          'Profile Search',
          'Input field to search GitHub username.',
          '- Display:',
          'Avatar.',
          'Name.',
          'Bio.',
          'Followers / Following.',
          'Public Repositories count.',
          'Repository Explorer',
          'List top repositories of the user.',
          '- Each repo card must show:',
          'Name.',
          'Stars.',
          'Forks.',
          'Language.',
          'Clicking a repo opens a detail view or modal.',
          'Frontend Core Requirements (Important)',
          '- UI & Responsiveness',
          'Must work properly on Mobile, Tablet, Desktop.',
          'Responsive grid or flex layout.',
          'No UI frameworks (Bootstrap/MUI not allowed).',
          'State & UX Handling',
          'Loading spinner while fetching.',
          '- Error state for:',

          'Invalid username.',
          'Network failure.',
          '"No repositories" empty state.',
          'Disable search button while loading.',
          'Code & Structure',
          'Component-based structure (if using React/Vue).',
          'Meaningful variable names.',
          'Separate API logic from UI logic.',
          'Comments explaining key logic.',
          'Constraints',
          'Only public GitHub API.',
          'No copy-paste UI templates.',
        ],
        link: '',
        criteria: [
          'API Handling- fetch/async-await/try-catch',
          'Responsiveness- Media queries / layout adaptability',
          'UI / UX- Spacing, readability, visual clarity',
          'State Logic- loading/error/empty',
          'Code quality- structure & naming',

          'Modern frontend framework like React.js or Vue.js. (optional)',
          'UI framework like Tailwind CSS, Bootstrap, or Material UI (optional)',
        ],
        browniePoints: [
          'Repository search filter',
          'Sort repos by stars/date',
          'Infinite scroll or pagination',
          'Save last searched profile in LocalStorage',
          'Display contribution graph (static mock allowed)',
        ],
        imageUrl: '',
      },
      {
        title: ' Task 2: Category Based Task Manager API',
        description: [
          'Task Overview',
          'Create a backend API for a simple task management system where tasks are organized under categories. The goal is to test understanding of basic backend structure, database usage, validation, and relations between entities.',
          'Functional Requirements',
          '1) Category Management',
          'Create a category (e.g., Study, Personal, Gym).',
          'Each category should have a name and createdAt field.',
          '',
          '',
          '2) Task Management',
          'Create a task under a specific category.',
          'Each task should have:',

          'title.',
          'description.',
          'completed (default: false).',
          'createdAt.',
          'categoryId (reference to category).',
          '3) Task Operations',
          'Mark a task as completed.',
          'Fetch all tasks belonging to a specific category.',

          'Required Endpoints',

          'POST /categories.',
          'POST /tasks.',
          'PATCH /tasks/:id/complete.',
          'GET /categories/:id/tasks.',

          'Technical Requirements',
          'Use any backend framework (Node.js with Express preferred).',
          'Use a database (MongoDB or PostgreSQL).',
          'Proper validation for required fields.',
          'Proper HTTP status codes.',
          'Clean folder structure (routes, models, controllers recommended).',
          'Error handling for invalid inputs and missing resources.',
        ],
        link: '',
        criteria: [
          'Proper schema design and relationship handling.',
          'Proper validation and error handling.',
          'Clean API structure and routing.',
          'Correct use of async operations.',
          'Meaningful status codes in responses.',
          'Code readability and organization.',
        ],
        browniePoints: [
          'Use of environment variables (include env.example in the repository).',
          'Split the code into folders (like controllers, routers, etc.) to keep the code modular.',
          'Proper use of middleware.',
          'Basic documentation in README (setup steps and API usage).',
          'Postman collection included.',
        ],
      },
    ],
  },
  {
    year: 2,
    tasks: [
      {
        title: 'Resume Enhancement Platform',
        description: [
          'Problem',
          'Job seekers often struggle to keep up with evolving job descriptions and tailor their resumes effectively.',
          'Project Overview',
          'Creating a platform that uses Generative AI to help job seekers tailor their resumes to specific job descriptions. By uploading a resume and job post, the system rewrites and aligns content using prompt engineering, boosting ATS compatibility and recruiter appeal.',
          'Core features:',
          '- User Uploads Resume (PDF)',
          'Resume is parsed and converted to text using OCR/NLP.',
          '- Job Description Input: ',
          'Either pasted as text or uploaded.',
          '- AI Matching Engine (Gemini): ',
          'Analyzes the job description for required skills, experiences, tools, and keywords.',
          'Compares with the resume.',
          'Suggests edits and rewrites content to better align with the job using Gemini or any other LLM model.',
        ],
        criteria: [
          'Backend: Node.js / Python',
          'AI/LLM: Google Gemini API or any other',
          'PDF Parsing: pick any library (eg pdf-parse for node.js)',
          'Frontend: React.js / Next.js / Vue.js or any framework of your choice.',
          ,
          'Storage: AWS S3 / Firebase for file handling (adding storage to the project is optional)',
          'DB: PostgreSQL / MongoDB (adding database to the project is optional)',
          'Auth: no authentication required',
        ],
        browniePoints: [
          'Match Score: Showing users a percentage-based similarity score between the resume and job description.',
          'Cover Letter Generator: Tailored cover letter based on the job + resume using LLMs.',
          'Skill Gap Analyzer: Telling users what skills/certifications to acquire to fit the role.',
          'ATS Simulation: Showing which parts of the resume are likely to be flagged or ignored by ATS.',
        ],
        link: '',
        imageUrl: '',
      },
      {
        title: 'Mood Tracking Application',
        description: [
          'Problem: ',
          'In todays fast-paced world, people often neglect their emotional well-being due to busy schedules and a lack of self-reflection. Without consistent mood tracking, it becomes difficult to identify emotional patterns, stress triggers, or mental health trends that could lead to burnout, anxiety, or depression.',
          'Project Overview: ',
          'Create a beautifully designed mood tracking web app that allows users to log their mood daily using an intuitive built-in calendar UI. The platform helps users visualize emotional trends over time, reflect on their mental health, and gain insights through simple journaling and color-coded emotion mapping.',
          'Core Feaures: ',
          '- Build in interactive Calendar UI',
          'Monthly view with clickable days.',
          'Color-coded mood entries (e.g., happy = yellow, anxious = red).',
          '- Daily Mood Logging',
          'Select mood from a set of emojis or tags (Happy, Sad, Angry, Anxious, Calm).',
          'Optional short journal entry (max 140 characters).',
          '- User Authentication is required',
          'JWT or OAuth.',
        ],
        browniePoints: [
          'Mood Visualization',
          'Graphs for weekly/monthly mood trends',
          'Highlight emotional highs/lows',
          'Editable Entries',
          'Click any past day to update mood or journal',
          'Light/Dark Mode Toggle',
        ],
        criteria: [
          'Backend: Node.js / Python',
          'DB: PostgreSQL / MongoDB (Supabase, Firebase)',
          'Auth: Pick any library you’re comfortable with',
          'Frontend: React.js / Next.js / Vue.js or any framework of your choice.',
          'Styling: Tailwind CSS / ShadCN or any other library',
          'Calender UI: Do your own research',
          'Charts library: Do your own research (optional feature)',
        ],
        link: '',
        imageUrl: '',
      },
      {
        title: ' Multi-Tenant Blogging Platform API',
        description: [
          'Problem: ',
          'Create a multi-tenant blogging platform backend API where multiple organizations (tenants) can independently manage their users and posts. Each tenant operates in isolation, with role-based access control and secure authentication. Each tenant will have: Its own users, Its own posts, Role-based permissions, Strict data isolation.',
          'There are only two roles in the system: ADMIN, MEMBER.',
          'Requirements: ',
          '1) Tenant Creation: ',
          'Each tenant includes: id, name, created_at.',
          '2) User Authentication:',
          'Users belong to exactly one tenant.',

          'User field: id,email (unique within tenant), password_hash, role( ADMIN OR MEMBER), tenant_id.',
          'Authentication: Email + password, JWT or token-based system.',
          '3) Role-Based Access Control:',
          'Both roles can create posts, Users can edit their own posts, Only ADMIN can edit or delete any post.',
          '4) Post Management:',
          'Post fields: Id, title, content, author_id, tenant_id, created_at, updated_at, deleted_at (soft delete required).',
          'Tech Stack:',
          'Backend: Node.js +Express / Python + FastAPI or Flask.',
          'Database: PostgreSQL or MongoDB.',
          'ORM: Prisma or Mongoose.',
          'Authentication: JWT.',
          'Password Hashing: Bcrypt.',
          'Submission Requirements:',
          '1) Public GitHub Repository (Mandatory)',
          'Repository must be public.',
          'Clear folder structure.',
          '.env.example file included (no secrets committed).',
          '2) README File (Mandatory)',
          'Include Project overview, Tech stack.',
          'Setup instructions (step-by-step), All endpoints must be documented.',
        ],
        browniePoints: [
          'Pagination – Large datasets are split into pages to improve performance and reduce response size using page and limit parameters.',
          'Filtering – Supports filtering data based on specific fields to return only relevant results and optimize data retrieval.',
          'Indexing – Database indexes are used on frequently queried fields to speed up search and filter operations.',
          'Include a Postman collection for easy API testing and integration.',
        ],
        criteria: [
          'Backend: Node.js / Python',
          'DB: PostgreSQL / MongoDB (Supabase, Firebase)',
          'Auth: Pick any library you’re comfortable with',
        ],
        link: '',
        imageUrl: '',
      },
    ],
  },
];
